/*
 * SPDX-FileCopyrightText: 2020 Jim Mussared
 * SPDX-License-Identifier: MIT
 */
#ifndef MICROPY_INCLUDED_CANMV_NIMBLE_PORT_H
#define MICROPY_INCLUDED_CANMV_NIMBLE_PORT_H

#define MICROPY_HW_BLE_UART_ID (0)
#define MICROPY_HW_BLE_UART_BAUDRATE (1000000)

#endif /* MICROPY_INCLUDED_CANMV_NIMBLE_PORT_H */
