include("$(MPY_DIR)/extmod/asyncio")
require("base64")
require("binascii")
require("gzip")
require("hashlib")
require("heapq")
require("mip")
require("urequests")
require("umqtt.robust")
require("umqtt.simple")

package("mpp", base_path="../builtin_py")
package("media", base_path="../builtin_py")
