#!/usr/bin/env python3
"""Generate CanMV K230 MicroPython stubs for IDE completion.

The generator is source/build based:
- frozen_mpy/ is used to inventory frozen Python modules for the selected board.
- genhdr/qstr/*.qstr is used to identify the C/C++ sources compiled for that board.
- C module globals, object types, locals dictionaries and mp_arg_t tables are parsed
  to discover names and first-pass signatures.
- tools/canmv_stub_overrides.json is only for polishing signatures/docs when C
  source does not preserve enough type or parameter information.

For standard MicroPython/library modules, bundle the matching micropython-stubs
package beside this CanMV overlay.
"""

from __future__ import annotations

import argparse
import ast
import json
import keyword
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Iterable

HEADER = """# Auto-generated by src/canmv/tools/gen_canmv_stubs.py.\n# CanMV K230 MicroPython stubs for IDE completion.\n\nfrom typing import Any, Optional\n\n"""

CANMV_DIR = Path(__file__).resolve().parents[1]
PORT_DIR = CANMV_DIR / "port"
MICROPY_DIR = CANMV_DIR / "micropython"
BUILTIN_PY_DIR = PORT_DIR / "builtin_py"
MICROPY_LIB_DIR = MICROPY_DIR / "lib" / "micropython-lib"
RESOURCE_LIBS_DIR = CANMV_DIR / "resources" / "libs"
DEFAULT_MANIFEST = PORT_DIR / "boards" / "manifest.py"
DEFAULT_OVERRIDES = CANMV_DIR / "tools" / "canmv_stub_overrides.json"

ENTRY_RE = re.compile(
    r"\{\s*MP_ROM_QSTR\(MP_QSTR_(?P<name>[A-Za-z0-9_]+)\)\s*,\s*(?P<rhs>[^}]+)\}",
    re.DOTALL,
)
ROM_MAP_RE = re.compile(
    r"(?:static\s+|STATIC\s+)?(?:const\s+)?mp_rom_map_elem_t\s+"
    r"(?P<name>[A-Za-z0-9_]+)\[\]\s*=\s*\{(?P<body>.*?)\};",
    re.DOTALL,
)
CONST_DICT_RE = re.compile(
    r"(?:STATIC\s+|static\s+)?MP_DEFINE_CONST_DICT\s*\(\s*(?P<dict>[A-Za-z0-9_]+)\s*,\s*(?P<table>[A-Za-z0-9_]+)\s*\)",
    re.DOTALL,
)
TYPE_RE = re.compile(r"MP_DEFINE_CONST_OBJ_TYPE\(\s*(?P<type>[A-Za-z0-9_]+)\s*,\s*MP_QSTR_(?P<qstr>[A-Za-z0-9_]+)\s*,(?P<body>.*?)\);", re.DOTALL)
MODULE_DEF_RE = re.compile(
    r"(?:const\s+)?mp_obj_module_t\s+(?P<var>[A-Za-z0-9_]+)\s*=\s*\{(?P<body>.*?)\};",
    re.DOTALL,
)
REGISTER_RE = re.compile(
    r"MP_REGISTER_(?:EXTENSIBLE_)?MODULE\(\s*MP_QSTR_(?P<module>[A-Za-z0-9_]+)\s*,\s*(?P<var>[A-Za-z0-9_]+)"
)
ARG_ENTRY_RE = re.compile(
    r"\{\s*MP_QSTR_(?P<name>[A-Za-z0-9_]+)\s*,\s*(?P<flags>.*?)\s*,\s*"
    r"\{\s*\.(?P<field>u_[A-Za-z0-9_]+)\s*=\s*(?P<default>.*?)\s*\}\s*\}",
    re.DOTALL,
)
FUN_OBJ_FIXED_RE = re.compile(r"MP_DEFINE_CONST_FUN_OBJ_(?P<argc>[0-9]+)\(\s*(?P<obj>[A-Za-z0-9_]+)_obj\s*,\s*(?P<func>[A-Za-z0-9_]+)")
FUN_OBJ_VAR_RE = re.compile(r"MP_DEFINE_CONST_FUN_OBJ_VAR(?:_BETWEEN)?\(\s*(?P<obj>[A-Za-z0-9_]+)_obj\s*,\s*(?P<min>[0-9]+)(?:\s*,\s*(?P<max>[0-9]+))?\s*,\s*(?P<func>[A-Za-z0-9_]+)")
FUN_OBJ_KW_RE = re.compile(r"MP_DEFINE_CONST_FUN_OBJ_KW\(\s*(?P<obj>[A-Za-z0-9_]+)_obj\s*,\s*(?P<min>[0-9]+)\s*,\s*(?P<func>[A-Za-z0-9_]+)")
STATICMETHOD_OBJ_RE = re.compile(
    r"MP_DEFINE_CONST_STATICMETHOD_OBJ\(\s*(?P<alias>[A-Za-z0-9_]+)\s*,\s*MP_ROM_PTR\(\s*&(?P<target>[A-Za-z0-9_]+)\s*\)\s*\)"
)
MP_ARG_CHECK_RE = re.compile(
    r"mp_arg_check_num\(\s*n_args\s*,\s*n_kw\s*,\s*(?P<min>[0-9]+)\s*,\s*(?P<max>[0-9]+|MP_OBJ_FUN_ARGS_MAX)\s*,\s*(?P<kw>true|false)\s*\)"
)
MP_ARG_PARSE_RE = re.compile(r"mp_arg_parse_all\(.*?allowed_args", re.DOTALL)
PTR_RE = re.compile(r"&(?P<var>[A-Za-z0-9_]+)")
STUB_DOC_LINE_RE = re.compile(r"^\s*(?://|#)\| ?(?P<text>.*)$")

OverrideMap = Dict[str, Dict[str, Any]]


@dataclass(frozen=True)
class PythonStubSource:
    module: str
    src: Path
    dst_rel: Path


@dataclass
class CFunction:
    obj: str
    func: str
    min_args: int | None = None
    max_args: int | None = None
    accepts_kw: bool = False
    allowed_args: list[str] = field(default_factory=list)
    arg_hints: dict[int, tuple[str, str]] = field(default_factory=dict)
    min_args_hint: int | None = None
    kw_hints: list[str] = field(default_factory=list)
    positional_only: bool = False
    is_staticmethod: bool = False


@dataclass
class CType:
    type_var: str
    qstr: str
    make_new: str | None = None
    locals_dict: str | None = None
    init_args: list[str] = field(default_factory=list)
    methods: dict[str, str] = field(default_factory=dict)
    attrs: dict[str, str] = field(default_factory=dict)


@dataclass
class CModule:
    name: str
    var: str
    globals_dict: str | None = None
    table: str | None = None
    source: str | None = None


@dataclass
class CAnalysis:
    sources: list[Path]
    functions: dict[str, CFunction] = field(default_factory=dict)
    types: dict[str, CType] = field(default_factory=dict)
    modules: dict[str, CModule] = field(default_factory=dict)
    table_bodies: dict[str, str] = field(default_factory=dict)
    dict_tables: dict[str, str] = field(default_factory=dict)
    module_extra_bodies: dict[str, str] = field(default_factory=dict)


def run_git(args: list[str], cwd: Path) -> str:
    try:
        return subprocess.check_output(args, cwd=str(cwd), stderr=subprocess.DEVNULL, text=True).strip()
    except Exception:
        return "unknown"


def clean_output(out_dir: Path) -> None:
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)


def micropython_version() -> str:
    config = MICROPY_DIR / "py" / "mpconfig.h"
    major = minor = micro = "0"
    if config.exists():
        for line in config.read_text(errors="ignore").splitlines():
            parts = line.split()
            if len(parts) >= 3 and parts[0] == "#define":
                if parts[1] == "MICROPY_VERSION_MAJOR":
                    major = parts[2]
                elif parts[1] == "MICROPY_VERSION_MINOR":
                    minor = parts[2]
                elif parts[1] == "MICROPY_VERSION_MICRO":
                    micro = parts[2]
    return f"{major}.{minor}.{micro}"


def default_build_dir() -> Path | None:
    output_dir = CANMV_DIR.parents[1] / "output"
    if not output_dir.exists():
        return None
    candidates = sorted(output_dir.glob("*/canmv"), key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0] if candidates else None


def remove_prefix(value: str, prefix: str) -> str:
    return value[len(prefix):] if value.startswith(prefix) else value


def remove_suffix(value: str, suffix: str) -> str:
    return value[:-len(suffix)] if suffix and value.endswith(suffix) else value


def qstr_module_name(name: str) -> str:
    return name.replace("_dot_", ".")


def collect_c_macros(text: str) -> dict[str, str]:
    macros: dict[str, str] = {}
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        stripped = line.lstrip()
        if not stripped.startswith("#define "):
            index += 1
            continue

        parts = stripped[len("#define "):].split(None, 1)
        if not parts:
            index += 1
            continue
        name = parts[0]
        body_parts = [parts[1] if len(parts) > 1 else ""]
        while body_parts[-1].rstrip().endswith("\\") and index + 1 < len(lines):
            body_parts[-1] = body_parts[-1].rstrip()[:-1]
            index += 1
            body_parts.append(lines[index])
        body = "\n".join(body_parts)
        # Prefer the first non-empty definition when multiple #define's
        # exist for the same name (e.g. inside #if / #else / #endif).
        if name not in macros or (not macros[name].strip() and body.strip()):
            macros[name] = body
        index += 1
    return macros


def expand_c_macro(name: str, macros: dict[str, str], seen: set[str] | None = None) -> str:
    if seen is None:
        seen = set()
    if name in seen:
        return ""
    body = macros.get(name, "")
    seen.add(name)
    for token in sorted(set(re.findall(r"\b[A-Z][A-Z0-9_]+\b", body))):
        if token in macros:
            body = re.sub(r"\b" + re.escape(token) + r"\b", expand_c_macro(token, macros, seen.copy()), body)
    return body


_INCLUDE_RE = re.compile(r'^\s*#\s*include\s+"(?P<path>[^"]+)"', re.MULTILINE)
_INCLUDE_SEARCH_DIRS: list[Path] | None = None


def _include_search_dirs() -> list[Path]:
    """Return project directories to search when resolving ``#include "..."``."""
    global _INCLUDE_SEARCH_DIRS
    if _INCLUDE_SEARCH_DIRS is None:
        dirs: list[Path] = []
        for root in (PORT_DIR, MICROPY_DIR, CANMV_DIR):
            if root.exists():
                dirs.append(root)
        _INCLUDE_SEARCH_DIRS = dirs
    return _INCLUDE_SEARCH_DIRS


def resolve_local_includes(source_path: Path) -> dict[str, str]:
    """Read source file, find ``#include "..."`` directives, resolve them against
    the project tree, and return a merged dict of all macros from those headers.
    """
    try:
        text = source_path.read_text(errors="ignore")
    except OSError:
        return {}
    macros: dict[str, str] = {}
    source_dir = source_path.parent
    search_dirs = [source_dir] + _include_search_dirs()
    seen: set[Path] = set()
    for match in _INCLUDE_RE.finditer(text):
        include_path = match.group("path")
        for base in search_dirs:
            candidate = (base / include_path).resolve()
            if candidate.exists() and candidate not in seen:
                seen.add(candidate)
                try:
                    header_text = candidate.read_text(errors="ignore")
                except OSError:
                    continue
                macros.update(collect_c_macros(header_text))
                break
    return macros


def expand_table_body_macros(body: str, macros: dict[str, str]) -> str:
    """Expand C preprocessor macros found inside a ROM table body.

    Only all-uppercase identifiers that reference known macros are expanded;
    everything else is left unchanged.
    """
    if not macros:
        return body
    # Find standalone uppercase identifiers that could be macros
    candidates = set(re.findall(r"\b([A-Z][A-Z0-9_]{2,})\b", body))
    result = body
    for name in sorted(candidates, key=len, reverse=True):
        if name in macros:
            expanded = expand_c_macro(name, macros)
            if expanded and expanded != name:
                result = result.replace(name, expanded)
    return result


def module_name_from_mpy(path: Path, root: Path) -> str:
    rel = path.relative_to(root).with_suffix("")
    parts = list(rel.parts)
    if parts and parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def discover_frozen_modules(build_dir: Path | None) -> list[str]:
    if build_dir is None:
        return []
    frozen_mpy = build_dir / "frozen_mpy"
    if not frozen_mpy.exists():
        return []
    return sorted({module_name_from_mpy(path, frozen_mpy) for path in frozen_mpy.rglob("*.mpy")})


def qstr_stem_to_source(qstr_file: Path) -> Path | None:
    """Map a .qstr filename back to its original C/C++ source file.

    Three naming conventions are handled:

    1. ``@@__micropython__extmod__modtime.c.qstr``
       Files from the MicroPython core (``MICROPY_DIR``).  Leading ``@@`` marks
       the canonical upstream tree; the remainder is a relative path with ``__``
       separators.

    2. ``drivers__sensor__sc2236.c.qstr``
       First-party port sources under ``PORT_DIR``.  No prefix ― the stem is a
       relative path from ``PORT_DIR`` with ``__`` separators.

    3. ``__home__...__output__...__lvgl__lv_mpy.c.qstr``
       Generated or out-of-tree sources whose QSTR stem is an absolute path
       encoded with ``__`` as directory separators.  These files live inside
       the build directory itself.
    """
    stem = remove_suffix(qstr_file.name, ".qstr")
    if stem.startswith("@@__micropython__"):
        rel = remove_prefix(stem, "@@__micropython__").replace("__", "/")
        src = MICROPY_DIR / rel
    elif stem.startswith("__"):
        # Absolute-path encoding: /home/.../output/.../lvgl/lv_mpy.c
        # becomes __home__...__output__...__lvgl__lv_mpy.c
        candidate = Path("/" + stem.replace("__", "/"))
        if candidate.exists():
            return candidate
        return None
    else:
        src = PORT_DIR / stem.replace("__", "/")
    return src if src.exists() else None


def discover_qstr_sources(build_dir: Path | None) -> list[Path]:
    if build_dir is None:
        return []
    qstr_dir = build_dir / "genhdr" / "qstr"
    if not qstr_dir.exists():
        return []
    sources = []
    for qstr_file in qstr_dir.glob("*.qstr"):
        src = qstr_stem_to_source(qstr_file)
        if src is not None:
            sources.append(src)
    return sorted(set(sources))


def discover_sibling_sources(qstr_sources: list[Path]) -> list[Path]:
    """Find C/C++ files that live in the same directory subtrees as *qstr_sources*
    but don't have their own .qstr file.  These are typically helper translation
    units (e.g. ``bitwise.c``, ``compare.c`` in ulab) whose function objects are
    referenced from another file's ROM table.
    """
    known = set(qstr_sources)
    result: list[Path] = []
    seen_dirs: set[Path] = set()
    for src in qstr_sources:
        parent = src.parent
        if parent in seen_dirs:
            continue
        seen_dirs.add(parent)
        # Walk up to 4 levels deep from the source directory
        for depth in range(5):
            search_root = parent
            for _ in range(depth):
                search_root = search_root.parent
            if not _is_within_project(search_root):
                continue
            for c_file in sorted(search_root.glob("*.c")):
                if c_file not in known and c_file not in result:
                    result.append(c_file)
            for cpp_file in sorted(search_root.glob("*.cpp")):
                if cpp_file not in known and cpp_file not in result:
                    result.append(cpp_file)
    return sorted(set(result))


def _is_within_project(path: Path) -> bool:
    """Return True if *path* is inside PORT_DIR or MICROPY_DIR."""
    try:
        path.resolve().relative_to(PORT_DIR.resolve())
        return True
    except ValueError:
        pass
    try:
        path.resolve().relative_to(MICROPY_DIR.resolve())
        return True
    except ValueError:
        pass
    return False


def fallback_sources() -> list[Path]:
    patterns = ("*.c", "*.cpp")
    sources: list[Path] = []
    for root in (PORT_DIR, MICROPY_DIR / "py", MICROPY_DIR / "extmod"):
        if root.exists():
            for pattern in patterns:
                sources.extend(root.rglob(pattern))
    return sorted(set(sources))


def load_overrides(path: Path | None) -> OverrideMap:
    if path is None or not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return {k: v for k, v in data.items() if not k.startswith("__")}


def module_override(overrides: OverrideMap, module: str) -> dict[str, Any]:
    override = overrides.get(module, {})
    return override if isinstance(override, dict) else {}


def module_symbols(overrides: OverrideMap, module: str) -> dict[str, Any]:
    symbols = module_override(overrides, module).get("symbols", {})
    return symbols if isinstance(symbols, dict) else {}


def deep_merge_dict(left: dict[str, Any], right: dict[str, Any]) -> dict[str, Any]:
    merged = dict(left)
    for key, value in right.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = deep_merge_dict(merged[key], value)
        else:
            merged[key] = value
    return merged


def merge_overrides(*maps: OverrideMap) -> OverrideMap:
    result: OverrideMap = {}
    for override_map in maps:
        for module, override in override_map.items():
            if not isinstance(override, dict):
                continue
            result[module] = deep_merge_dict(result.get(module, {}), override)
    return result


def signature_from_stub_node(lines: list[str], node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    line = lines[node.lineno - 1]
    match = re.match(r"\s*(?:async\s+def|def)\s+" + re.escape(node.name) + r"\s*(?P<sig>\(.*\)\s*(?:->\s*[^:]+)?)\s*:", line)
    return ensure_signature(match.group("sig"), format_signature(node)) if match else format_signature(node)


def annotation_from_stub_assignment(lines: list[str], node: ast.Assign | ast.AnnAssign) -> str:
    if isinstance(node, ast.AnnAssign):
        line = lines[node.lineno - 1]
        match = re.match(r"\s*[A-Za-z_][A-Za-z0-9_]*\s*:\s*(?P<typ>[^=#]+)", line)
        if match:
            return match.group("typ").strip()
    return "Any"


def stub_doc_block_to_override(default_module: str | None, block_lines: list[str]) -> OverrideMap:
    module = default_module
    body_lines: list[str] = []
    for line in block_lines:
        match = re.match(r"\s*module\s*:\s*(?P<module>[A-Za-z_][A-Za-z0-9_.]*)\s*$", line)
        if match:
            module = match.group("module")
        else:
            body_lines.append(line)
    if not module or not any(line.strip() for line in body_lines):
        return {}

    text = "\n".join(body_lines)
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return {}

    lines = text.splitlines()
    module_data: dict[str, Any] = {}
    module_doc = ast.get_docstring(tree)
    if module_doc:
        module_data["doc"] = module_doc
    symbols: dict[str, Any] = {}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and public_name(node.name):
            symbols[node.name] = {
                "kind": "function",
                "signature": signature_from_stub_node(lines, node),
            }
            doc = ast.get_docstring(node)
            if doc:
                symbols[node.name]["doc"] = doc
        elif isinstance(node, ast.ClassDef) and public_name(node.name):
            class_override: dict[str, Any] = {"kind": "class"}
            doc = ast.get_docstring(node)
            if doc:
                class_override["doc"] = doc
            methods: dict[str, Any] = {}
            attrs: dict[str, str] = {}
            for item in node.body:
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)) and public_name(item.name):
                    method = {"signature": signature_from_stub_node(lines, item)}
                    method_doc = ast.get_docstring(item)
                    if method_doc:
                        method["doc"] = method_doc
                    if item.name == "__init__":
                        class_override["init"] = method["signature"]
                        if method_doc:
                            class_override["init_doc"] = method_doc
                    else:
                        methods[item.name] = method
                elif isinstance(item, (ast.Assign, ast.AnnAssign)):
                    name = is_public_assignment(item)
                    if name:
                        attrs[name] = annotation_from_stub_assignment(lines, item)
            if methods:
                class_override["methods"] = methods
            if attrs:
                class_override["attrs"] = attrs
            symbols[node.name] = class_override
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            name = is_public_assignment(node)
            if name:
                symbols[name] = {"kind": "const", "type": annotation_from_stub_assignment(lines, node)}
    if symbols:
        module_data["symbols"] = symbols
    return {module: module_data} if module_data else {}


def port_doc_overrides_from_file(path: Path, default_module: str | None = None) -> OverrideMap:
    try:
        path.resolve().relative_to(PORT_DIR.resolve())
    except ValueError:
        return {}

    overrides: OverrideMap = {}
    block: list[str] = []
    for line in path.read_text(errors="ignore").splitlines():
        match = STUB_DOC_LINE_RE.match(line)
        if match:
            block.append(match.group("text"))
            continue
        if block:
            overrides = merge_overrides(overrides, stub_doc_block_to_override(default_module, block))
            block = []
    if block:
        overrides = merge_overrides(overrides, stub_doc_block_to_override(default_module, block))
    return overrides


def collect_port_doc_overrides(analysis: CAnalysis, manifest_sources: list[PythonStubSource]) -> OverrideMap:
    source_default_modules: dict[Path, str | None] = {}
    module_sources: dict[Path, list[str]] = {}
    for module in analysis.modules.values():
        if module.source:
            module_sources.setdefault(Path(module.source).resolve(), []).append(module.name)
    for path, modules in module_sources.items():
        source_default_modules[path] = modules[0] if len(modules) == 1 else None
    for source in manifest_sources:
        source_default_modules[source.src.resolve()] = source.module
    for source in analysis.sources:
        source_default_modules.setdefault(source.resolve(), None)

    overrides: OverrideMap = {}
    for path, default_module in sorted(source_default_modules.items()):
        if path.exists():
            overrides = merge_overrides(overrides, port_doc_overrides_from_file(path, default_module))
    return overrides


def doc_lines(doc: str | None, indent: str) -> list[str]:
    return [indent + json.dumps(doc)] if doc else []


def class_signature_is_static(signature: str) -> bool:
    match = re.match(r"\((?P<args>.*?)\)\s*->", signature.strip())
    if not match:
        return False
    args_text = match.group("args").strip()
    if not args_text:
        return True
    for part in args_text.split(","):
        name = part.strip().split(":", 1)[0].split("=", 1)[0].strip()
        if name in {"*", "/"}:
            continue
        if name.startswith("*"):
            return True
        return name not in {"self", "cls"}
    return True


def class_method_decorators(signature: str, explicit: list[str] | None = None) -> list[str] | None:
    decorators = list(explicit or [])
    if not decorators and class_signature_is_static(signature):
        decorators.append("@staticmethod")
    return decorators or None


def ensure_signature(signature: str | None, fallback: str) -> str:
    if not signature:
        return fallback
    signature = signature.strip()
    return signature if signature.startswith("(") else "(" + signature


def render_function(
    name: str,
    signature: str,
    doc: str | None = None,
    indent: str = "",
    prefix: str = "def",
    decorators: list[str] | None = None,
) -> list[str]:
    lines = [f"{indent}{decorator}" for decorator in decorators or []]
    lines.append(f"{indent}{prefix} {name}{signature}:")
    lines.extend(doc_lines(doc, indent + "    "))
    lines.append(f"{indent}    ...")
    return lines


def render_class(
    name: str,
    override: dict[str, Any] | None = None,
    methods: dict[str, str] | None = None,
    attrs: dict[str, str] | None = None,
    add_default_init: bool = True,
) -> list[str]:
    override = override or {}
    methods = dict(methods or {})
    attrs = attrs or {}
    lines = [f"class {name}:"]
    lines.extend(doc_lines(override.get("doc"), "    "))

    merged_attrs = dict(attrs)
    override_attrs = override.get("attrs", {})
    if isinstance(override_attrs, dict):
        merged_attrs.update(override_attrs)
    for attr, typ in sorted(merged_attrs.items()):
        if valid_stub_identifier(attr):
            lines.append(f"    {attr}: {typ or 'Any'}")

    generated_init_sig = methods.pop("__init__", None)
    init_sig = override.get("init") or generated_init_sig
    if init_sig:
        lines.extend(render_function("__init__", ensure_signature(init_sig, "(self, *args: Any, **kwargs: Any) -> None"), override.get("init_doc"), "    "))
    elif add_default_init:
        lines.extend(render_function("__init__", "(self, *args: Any, **kwargs: Any) -> None", None, "    "))

    method_overrides = override.get("methods", {})
    method_overrides = method_overrides if isinstance(method_overrides, dict) else {}
    seen_methods = set()
    for method_name, signature in sorted(methods.items()):
        if not valid_stub_identifier(method_name):
            continue
        method_override = method_overrides.get(method_name, {})
        method_override = method_override if isinstance(method_override, dict) else {}
        final_sig = ensure_signature(method_override.get("signature"), signature)
        lines.extend(render_function(method_name, final_sig, method_override.get("doc"), "    ", decorators=class_method_decorators(final_sig)))
        seen_methods.add(method_name)

    for method_name, method_override in sorted(method_overrides.items()):
        if not valid_stub_identifier(method_name):
            continue
        if method_name in seen_methods or not isinstance(method_override, dict):
            continue
        final_sig = ensure_signature(method_override.get("signature"), "(self, *args: Any, **kwargs: Any) -> Any")
        lines.extend(render_function(method_name, final_sig, method_override.get("doc"), "    ", decorators=class_method_decorators(final_sig)))

    if len(lines) == 1:
        lines.append("    pass")
    lines.append("")
    return lines


def render_override_symbol(name: str, override: dict[str, Any]) -> list[str]:
    kind = override.get("kind", "function")
    if kind == "class":
        return render_class(name, override)
    if kind == "const":
        return [f"{name}: {override.get('type', 'Any')}"]
    if kind == "module":
        return [f"{name}: Any"]
    return render_function(name, ensure_signature(override.get("signature"), "(*args: Any, **kwargs: Any) -> Any"), override.get("doc"))


def valid_stub_identifier(name: str) -> bool:
    return name.isidentifier() and not keyword.iskeyword(name)


def public_name(name: str) -> bool:
    return valid_stub_identifier(name) and (not name.startswith("_") or name in {"__init__", "__enter__", "__exit__"})


def import_line(source_lines: list[str], node: ast.Import | ast.ImportFrom) -> str:
    """Render imports for .pyi files.

    Pyright/Pylance treats imported names in stub files as private unless they
    are explicitly re-exported, normally by using a redundant alias such as
    ``from _media import Display as Display``.  The generated Python package
    stubs are often thin wrappers around C extension modules, so their imported
    public names must remain visible to IDE completion.
    """
    if isinstance(node, ast.ImportFrom):
        module = "." * node.level + (node.module or "")
        rendered: list[str] = []
        for alias in node.names:
            if alias.name == "*":
                rendered.append("*")
            elif alias.asname:
                rendered.append(f"{alias.name} as {alias.asname}")
            else:
                rendered.append(f"{alias.name} as {alias.name}")
        return f"from {module} import {', '.join(rendered)}"

    rendered_imports: list[str] = []
    for alias in node.names:
        if alias.asname:
            rendered_imports.append(f"{alias.name} as {alias.asname}")
        elif "." not in alias.name:
            rendered_imports.append(f"{alias.name} as {alias.name}")
        else:
            rendered_imports.append(alias.name)
    return f"import {', '.join(rendered_imports)}"


def annotation_text(annotation: ast.expr | None) -> str | None:
    if annotation is None:
        return None
    try:
        return ast.unparse(annotation)
    except Exception:
        return None


def default_text(default: ast.expr | None) -> str | None:
    if default is None:
        return None
    if isinstance(default, ast.Constant):
        return repr(default.value)
    if isinstance(default, ast.Name):
        return default.id
    if isinstance(default, ast.Attribute):
        try:
            return ast.unparse(default)
        except Exception:
            return "..."
    if isinstance(default, ast.UnaryOp) and isinstance(default.op, (ast.UAdd, ast.USub)) and isinstance(default.operand, ast.Constant):
        try:
            return ast.unparse(default)
        except Exception:
            return "..."
    return "..."


def kwarg_default_text(default: ast.expr | None) -> str:
    if default is None:
        return "..."
    if isinstance(default, ast.Constant):
        return repr(default.value)
    if isinstance(default, ast.Name) and default.id.isupper():
        return default.id
    if isinstance(default, ast.Attribute):
        try:
            return ast.unparse(default)
        except Exception:
            return "..."
    if isinstance(default, ast.UnaryOp) and isinstance(default.op, (ast.UAdd, ast.USub)) and isinstance(default.operand, ast.Constant):
        try:
            return ast.unparse(default)
        except Exception:
            return "..."
    return "..."


class KwargHintVisitor(ast.NodeVisitor):
    def __init__(self, kwarg_name: str) -> None:
        self.kwarg_name = kwarg_name
        self.hints: list[tuple[str, str]] = []
        self.seen: set[str] = set()

    def add(self, name: str, default: ast.expr | None = None) -> None:
        if name in self.seen or not valid_stub_identifier(name):
            return
        self.seen.add(name)
        self.hints.append((name, kwarg_default_text(default)))

    def visit_Call(self, node: ast.Call) -> Any:
        func = node.func
        if (
            isinstance(func, ast.Attribute)
            and func.attr == "get"
            and isinstance(func.value, ast.Name)
            and func.value.id == self.kwarg_name
            and node.args
            and isinstance(node.args[0], ast.Constant)
            and isinstance(node.args[0].value, str)
        ):
            self.add(node.args[0].value, node.args[1] if len(node.args) > 1 else None)
        self.generic_visit(node)

    def visit_Compare(self, node: ast.Compare) -> Any:
        if (
            isinstance(node.left, ast.Constant)
            and isinstance(node.left.value, str)
            and any(isinstance(op, ast.In) for op in node.ops)
            and any(isinstance(comp, ast.Name) and comp.id == self.kwarg_name for comp in node.comparators)
        ):
            self.add(node.left.value)
        self.generic_visit(node)

    def visit_Subscript(self, node: ast.Subscript) -> Any:
        if isinstance(node.value, ast.Name) and node.value.id == self.kwarg_name:
            key = node.slice
            if isinstance(key, ast.Constant) and isinstance(key.value, str):
                self.add(key.value)
        self.generic_visit(node)


def kwarg_hints_from_body(node: ast.FunctionDef | ast.AsyncFunctionDef, kwarg_name: str | None) -> list[tuple[str, str]]:
    if not kwarg_name:
        return []
    visitor = KwargHintVisitor(kwarg_name)
    for stmt in node.body:
        visitor.visit(stmt)
    return visitor.hints


def format_arg(arg: ast.arg, default: ast.expr | None = None, *, prefix: str = "") -> str:
    text = prefix + arg.arg
    annotation = annotation_text(arg.annotation)
    if annotation:
        text += f": {annotation}"
    rendered_default = default_text(default)
    if rendered_default is not None:
        text += f" = {rendered_default}"
    return text


def format_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    args = node.args
    parts: list[str] = []
    positional = list(getattr(args, "posonlyargs", [])) + list(args.args)
    default_offset = len(positional) - len(args.defaults)
    for index, arg in enumerate(positional):
        default = args.defaults[index - default_offset] if index >= default_offset else None
        parts.append(format_arg(arg, default))
        if getattr(args, "posonlyargs", []) and index == len(args.posonlyargs) - 1:
            parts.append("/")
    if args.vararg:
        parts.append(format_arg(args.vararg, prefix="*"))
    elif args.kwonlyargs:
        parts.append("*")
    for kwarg, default in zip(args.kwonlyargs, args.kw_defaults):
        parts.append(format_arg(kwarg, default))
    if args.kwarg:
        kwarg_hints = kwarg_hints_from_body(node, args.kwarg.arg)
        if kwarg_hints:
            if not args.vararg and "*" not in parts:
                parts.append("*")
            used_names = {part.split(":", 1)[0].split("=", 1)[0].strip().lstrip("*") for part in parts}
            for name, default in kwarg_hints:
                if name not in used_names:
                    parts.append(f"{name} = {default}")
                    used_names.add(name)
        parts.append(format_arg(args.kwarg, prefix="**"))
    return_type = annotation_text(node.returns) or ("None" if node.name == "__init__" else "Any")
    return "(" + ", ".join(parts) + f") -> {return_type}"


def is_public_assignment(node: ast.Assign | ast.AnnAssign) -> str | None:
    target = node.targets[0] if isinstance(node, ast.Assign) and len(node.targets) == 1 else None
    if isinstance(node, ast.AnnAssign):
        target = node.target
    if isinstance(target, ast.Name) and public_name(target.id):
        return target.id
    return None


def decorator_text(decorator: ast.expr) -> str | None:
    if isinstance(decorator, ast.Name) and decorator.id in {"classmethod", "staticmethod"}:
        return f"@{decorator.id}"
    return None


def rendered_decorators(node: ast.FunctionDef | ast.AsyncFunctionDef) -> list[str]:
    decorators = [decorator_text(decorator) for decorator in node.decorator_list]
    return [decorator for decorator in decorators if decorator]


def decorator_names(node: ast.ClassDef) -> set[str]:
    names: set[str] = set()
    for item in node.body:
        if not isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in item.decorator_list:
            if isinstance(decorator, ast.Name):
                names.add(decorator.id)
    return names


def class_methods_from_ast(node: ast.ClassDef, symbol_override: dict[str, Any]) -> tuple[dict[str, dict[str, Any]], dict[str, str]]:
    methods: dict[str, dict[str, Any]] = {}
    attrs: dict[str, str] = {}
    attr_overrides = symbol_override.get("attrs", {}) if isinstance(symbol_override, dict) else {}
    attr_overrides = attr_overrides if isinstance(attr_overrides, dict) else {}
    local_decorators = decorator_names(node)
    for item in node.body:
        if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)) and public_name(item.name):
            if item.name in local_decorators and not item.decorator_list:
                continue
            methods[item.name] = {
                "signature": format_signature(item),
                "doc": ast.get_docstring(item),
                "decorators": rendered_decorators(item),
                "prefix": "async def" if isinstance(item, ast.AsyncFunctionDef) else "def",
            }
        elif isinstance(item, (ast.Assign, ast.AnnAssign)):
            name = is_public_assignment(item)
            if name and name not in attr_overrides:
                annotation = annotation_text(item.annotation) if isinstance(item, ast.AnnAssign) else None
                attrs[name] = annotation or "Any"
    return methods, attrs


def render_python_class(node: ast.ClassDef, override: dict[str, Any] | None = None) -> list[str]:
    override = override or {}
    methods, attrs = class_methods_from_ast(node, override)
    lines = [f"class {node.name}:"]
    lines.extend(doc_lines(override.get("doc") or ast.get_docstring(node), "    "))

    merged_attrs = dict(attrs)
    override_attrs = override.get("attrs", {})
    if isinstance(override_attrs, dict):
        merged_attrs.update(override_attrs)
    for attr, typ in sorted(merged_attrs.items()):
        if valid_stub_identifier(attr):
            lines.append(f"    {attr}: {typ or 'Any'}")

    generated_init = methods.pop("__init__", None)
    init_sig = override.get("init") or (generated_init or {}).get("signature")
    if init_sig:
        lines.extend(
            render_function(
                "__init__",
                ensure_signature(init_sig, "(self, *args: Any, **kwargs: Any) -> None"),
                override.get("init_doc") or (generated_init or {}).get("doc"),
                "    ",
                decorators=class_method_decorators(ensure_signature(init_sig, "(self, *args: Any, **kwargs: Any) -> None"), (generated_init or {}).get("decorators")),
            )
        )

    nested_overrides = override.get("symbols", {})
    nested_overrides = nested_overrides if isinstance(nested_overrides, dict) else {}
    for item in node.body:
        if isinstance(item, ast.ClassDef) and public_name(item.name):
            nested_override = nested_overrides.get(item.name, {})
            nested_override = nested_override if isinstance(nested_override, dict) else {}
            nested_lines = render_python_class(item, nested_override)
            lines.extend("    " + line if line else line for line in nested_lines)

    method_overrides = override.get("methods", {})
    method_overrides = method_overrides if isinstance(method_overrides, dict) else {}
    seen_methods = set()
    for method_name, method in sorted(methods.items()):
        if not valid_stub_identifier(method_name):
            continue
        method_override = method_overrides.get(method_name, {})
        method_override = method_override if isinstance(method_override, dict) else {}
        final_sig = ensure_signature(method_override.get("signature"), method["signature"])
        lines.extend(
            render_function(
                method_name,
                final_sig,
                method_override.get("doc") or method.get("doc"),
                "    ",
                prefix=method.get("prefix", "def"),
                decorators=class_method_decorators(final_sig, method.get("decorators")),
            )
        )
        seen_methods.add(method_name)

    for method_name, method_override in sorted(method_overrides.items()):
        if not valid_stub_identifier(method_name):
            continue
        if method_name in seen_methods or not isinstance(method_override, dict):
            continue
        final_sig = ensure_signature(method_override.get("signature"), "(self, *args: Any, **kwargs: Any) -> Any")
        lines.extend(render_function(method_name, final_sig, method_override.get("doc"), "    "))

    if len(lines) == 1 or (len(lines) == 2 and lines[1].lstrip().startswith('"')):
        lines.append("    pass")
    lines.append("")
    return lines


def python_to_pyi(src: Path, dst: Path, module: str, overrides: OverrideMap) -> None:
    text = src.read_text(errors="ignore")
    try:
        tree = ast.parse(text, filename=str(src))
    except SyntaxError as exc:
        dst.write_text(HEADER + f"# Could not parse {src.name}: {exc}\n", encoding="utf-8")
        return

    source_lines = text.splitlines()
    module_doc = module_override(overrides, module).get("doc") or ast.get_docstring(tree)
    symbols = module_symbols(overrides, module)
    lines: list[str] = [HEADER.rstrip(), ""]
    lines.extend(doc_lines(module_doc, ""))
    if module_doc:
        lines.append("")
    imports: list[str] = []
    body_lines: list[str] = []
    seen: set[str] = set()

    def add_import(node: ast.Import | ast.ImportFrom) -> None:
        """Preserve import as explicit re-export for .pyi / Pylance.

        Examples:
            import image
                -> import image as image

            from _media import Display
                -> from _media import Display as Display

        This makes symbols imported by wrapper modules visible to Pyright/Pylance.
        """
        if isinstance(node, ast.Import):
            for alias in node.names:
                # Keep existing alias untouched.
                if alias.asname:
                    imports.append(f"import {alias.name} as {alias.asname}")
                else:
                    public_alias = alias.name.split(".", 1)[0]
                    imports.append(f"import {alias.name} as {public_alias}")
            return

        if isinstance(node, ast.ImportFrom):
            # Keep relative import dots.
            module_prefix = "." * node.level + (node.module or "")
            imported: list[str] = []

            for alias in node.names:
                if alias.name == "*":
                    imported.append("*")
                elif alias.asname:
                    imported.append(f"{alias.name} as {alias.asname}")
                else:
                    imported.append(f"{alias.name} as {alias.name}")

            imports.append(f"from {module_prefix} import {', '.join(imported)}")

    def collect_try_imports(node: ast.Try) -> None:
        """Collect safe top-level imports inside try/else blocks.

        Handles wrappers like:

            try:
                from _media import UVC
            except:
                raise NotImplementedError(...)
        """
        for item in list(node.body) + list(node.orelse):
            if isinstance(item, (ast.Import, ast.ImportFrom)):
                add_import(item)

    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            add_import(node)

        elif isinstance(node, ast.Try):
            collect_try_imports(node)

        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and public_name(node.name):
            override = symbols.get(node.name, {})
            override = override if isinstance(override, dict) else {}
            prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
            body_lines.extend(
                render_function(
                    node.name,
                    ensure_signature(override.get("signature"), format_signature(node)),
                    override.get("doc") or ast.get_docstring(node),
                    prefix=prefix,
                    decorators=rendered_decorators(node),
                )
            )
            seen.add(node.name)
        elif isinstance(node, ast.ClassDef) and public_name(node.name):
            override = symbols.get(node.name, {})
            override = override if isinstance(override, dict) else {}
            body_lines.extend(render_python_class(node, override))
            seen.add(node.name)
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            name = is_public_assignment(node)
            if name:
                override = symbols.get(name, {})
                override = override if isinstance(override, dict) else {}
                body_lines.append(f"{name}: {override.get('type', 'Any')}")
                seen.add(name)

    for name, override in symbols.items():
        if name not in seen and isinstance(override, dict):
            body_lines.extend(render_override_symbol(name, override))

    for line in imports:
        if line not in lines:
            lines.append(line)
    if imports:
        lines.append("")
    lines.extend(body_lines or ["..."])
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def manifest_path_from_build(build_dir: Path | None) -> Path:
    if build_dir is not None:
        board = remove_suffix(build_dir.parent.name, "_defconfig")
        manifest = PORT_DIR / "boards" / board / "manifest.py"
        if manifest.exists():
            return manifest
    return DEFAULT_MANIFEST


def expand_manifest_path(value: str, manifest_dir: Path, *, manifest_if_dir: bool = True) -> Path:
    value = value.replace("$(MPY_DIR)", str(MICROPY_DIR))
    value = value.replace("$(PORT_DIR)", str(PORT_DIR))
    value = value.replace("$(BOARD_DIR)", str(manifest_dir))
    path = Path(value)
    if not path.is_absolute():
        path = manifest_dir / path
    if manifest_if_dir and path.is_dir():
        path = path / "manifest.py"
    return path.resolve()


def module_from_rel(rel: Path, package: str | None = None) -> str:
    no_suffix = rel.with_suffix("")
    parts = list(no_suffix.parts)
    if parts and parts[-1] == "__init__":
        parts.pop()
    if package:
        parts = package.split(".") + parts
    return ".".join(parts)


def dst_rel_from_module_file(filename: str | Path) -> Path:
    return Path(filename).with_suffix(".pyi")


class ManifestResolver:
    def __init__(self) -> None:
        self.sources: dict[str, PythonStubSource] = {}
        self.seen_manifests: set[Path] = set()
        self.require_index: dict[str, Path] | None = None

    def add_source(self, module: str, src: Path, dst_rel: Path) -> None:
        if src.exists() and module:
            self.sources[module] = PythonStubSource(module, src.resolve(), dst_rel)

    def resolve_base(self, manifest_dir: Path, base_path: str | None) -> Path:
        path = expand_manifest_path(base_path or ".", manifest_dir, manifest_if_dir=False)
        return path.parent if path.name == "manifest.py" else path

    def module(self, manifest_dir: Path, filename: str, *args: Any, base_path: str | None = None, **kwargs: Any) -> None:
        base = self.resolve_base(manifest_dir, base_path)
        src = (base / filename).resolve()
        rel = Path(filename)
        dst_rel = dst_rel_from_module_file(rel)
        module = module_from_rel(rel)
        self.add_source(module, src, dst_rel)

    def package(self, manifest_dir: Path, name: str, files: Any = None, *args: Any, base_path: str | None = None, **kwargs: Any) -> None:
        base = self.resolve_base(manifest_dir, base_path)
        package_root = (base / name).resolve()
        package_dst = Path(*name.split("."))
        if isinstance(files, str):
            file_list = [files]
        elif files is None:
            file_list = [str(path.relative_to(package_root)) for path in sorted(package_root.rglob("*.py"))] if package_root.exists() else []
        else:
            file_list = list(files)
        for filename in file_list:
            src = (package_root / filename).resolve()
            rel = Path(filename)
            dst_rel = package_dst / rel.with_suffix(".pyi")
            module = module_from_rel(rel, name)
            self.add_source(module, src, dst_rel)

    def freeze(self, manifest_dir: Path, path: str, scripts: Any = None, *args: Any, **kwargs: Any) -> None:
        base = expand_manifest_path(path, manifest_dir, manifest_if_dir=False)
        if scripts is None:
            py_files = sorted(base.rglob("*.py")) if base.exists() else []
        elif isinstance(scripts, str):
            py_files = [base / scripts]
        else:
            py_files = [base / item for item in scripts]
        for src in py_files:
            if src.name.startswith("_") and src.name != "__init__.py":
                continue
            rel = src.relative_to(base)
            self.add_source(module_from_rel(rel), src, rel.with_suffix(".pyi"))

    def build_require_index(self) -> dict[str, Path]:
        index: dict[str, Path] = {}
        if not MICROPY_LIB_DIR.exists():
            return index
        for manifest in sorted(MICROPY_LIB_DIR.rglob("manifest.py")):
            package_dir = manifest.parent
            rel = package_dir.relative_to(MICROPY_LIB_DIR)
            keys = {package_dir.name, ".".join(rel.parts[1:]) if len(rel.parts) > 1 else package_dir.name}
            for key in keys:
                if key and key not in index:
                    index[key] = manifest
        return index

    def require(self, name: str, *args: Any, **kwargs: Any) -> None:
        if self.require_index is None:
            self.require_index = self.build_require_index()
        manifest = self.require_index.get(name)
        if manifest is not None:
            self.read_manifest(manifest)

    def read_manifest(self, manifest: Path) -> None:
        manifest = manifest.resolve()
        if manifest in self.seen_manifests or not manifest.exists():
            return
        self.seen_manifests.add(manifest)
        manifest_dir = manifest.parent
        env = {
            "include": lambda path, *args, **kwargs: self.read_manifest(expand_manifest_path(path, manifest_dir)),
            "require": self.require,
            "module": lambda filename, *args, **kwargs: self.module(manifest_dir, filename, *args, **kwargs),
            "package": lambda name, *args, **kwargs: self.package(manifest_dir, name, *args, **kwargs),
            "freeze": lambda path, *args, **kwargs: self.freeze(manifest_dir, path, *args, **kwargs),
            "metadata": lambda *args, **kwargs: None,
        }
        exec(compile(manifest.read_text(encoding="utf-8"), str(manifest), "exec"), {"__builtins__": {}}, env)


def discover_manifest_python_sources(manifest: Path | None) -> list[PythonStubSource]:
    if manifest is None or not manifest.exists():
        return []
    resolver = ManifestResolver()
    resolver.read_manifest(manifest)
    return sorted(resolver.sources.values(), key=lambda item: item.module)


def generate_python_package_stubs(
    out_dir: Path,
    overrides: OverrideMap,
    frozen_modules: set[str] | None = None,
    manifest_sources: list[PythonStubSource] | None = None,
) -> int:
    sources = manifest_sources or []
    if not sources:
        for package in ("media", "mpp"):
            src_root = BUILTIN_PY_DIR / package
            if not src_root.exists():
                continue
            for src in sorted(src_root.rglob("*.py")):
                rel = src.relative_to(BUILTIN_PY_DIR).with_suffix(".pyi")
                module = rel.with_suffix("").as_posix().replace("/", ".")
                if module.endswith(".__init__"):
                    module = module[: -len(".__init__")]
                sources.append(PythonStubSource(module, src, rel))

    count = 0
    for source in sources:
        top_level = source.module.split(".", 1)[0]
        if frozen_modules and source.module not in frozen_modules and top_level not in frozen_modules:
            continue
        python_to_pyi(source.src, out_dir / source.dst_rel, source.module, overrides)
        count += 1
    return count


def parse_default(field: str, value: str) -> str:
    value = value.strip()
    if field == "u_bool":
        return {"true": "True", "false": "False", "mp_const_true": "True", "mp_const_false": "False"}.get(value, "...")
    if value == "mp_const_none":
        return "None"
    if field == "u_obj":
        return "..."
    if re.fullmatch(r"-?0x[0-9A-Fa-f]+|-?[0-9]+", value):
        return value
    return "..."


def strip_c_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//.*", "", text)
    return text


def arg_type(flags: str, field: str) -> str:
    if "MP_ARG_BOOL" in flags or field == "u_bool":
        return "bool"
    if "MP_ARG_INT" in flags or field == "u_int":
        return "int"
    return "Any"


def normalize_arg_name(name: str) -> str:
    name = name.strip().split(".")[-1]
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    name = re.sub(r"_obj$|_in$|_out$", "", name)
    name = name.strip("_") or "arg"
    if name.startswith("arg_"):
        name = name[4:]
    if name.startswith("in_"):
        name = "input_" + name[3:]
    elif name.startswith("out_"):
        name = "output_" + name[4:]
    if name in {"type", "from", "class", "global", "async", "await"} or not valid_stub_identifier(name):
        name = name + "_"
    if name == "self":
        name = "obj"
    return name


def converter_arg_type(expr: str) -> str:
    if "mp_obj_is_true" in expr:
        return "bool"
    if "mp_obj_get_int" in expr or "mp_obj_get_uint" in expr:
        return "int"
    if "mp_obj_get_float" in expr:
        return "float"
    if "mp_obj_str_get_str" in expr or "mp_obj_str_get_data" in expr:
        return "str"
    if "mp_get_buffer" in expr:
        return "Any"
    return "Any"


def prefer_arg_hint(current: tuple[str, str] | None, candidate: tuple[str, str]) -> tuple[str, str]:
    if current is None:
        return candidate
    current_name, current_type = current
    candidate_name, candidate_type = candidate
    if current_name.startswith("arg") and not candidate_name.startswith("arg"):
        return candidate
    if current_type == "Any" and candidate_type != "Any":
        return (current_name, candidate_type)
    return current


def function_decl_arg_hints(text: str, func_name: str) -> dict[int, tuple[str, str]]:
    pattern = re.compile(
        r"(?:STATIC\s+|static\s+)?(?:mp_obj_t|void|int|bool|STATIC\s+mp_obj_t)\s+"
        + re.escape(func_name)
        + r"\s*\((?P<params>[^)]*)\)",
        re.DOTALL,
    )
    match = pattern.search(text)
    if not match:
        return {}
    hints: dict[int, tuple[str, str]] = {}
    params = [part.strip() for part in match.group("params").split(",") if part.strip()]
    hidden_params = {"type", "n_args", "n_kw", "args", "all_args", "pos_args", "kw_args", "kwargs"}
    for index, param in enumerate(params):
        if param == "void":
            continue
        name_match = re.search(r"(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*(?:\[[^]]*\])?$", param.replace("*", " "))
        if not name_match:
            continue
        raw_name = name_match.group("name")
        if raw_name in hidden_params:
            continue
        name = normalize_arg_name(raw_name)
        hints[index] = (name, "Any")
    return hints


def infer_arg_hints(text: str, func_name: str) -> dict[int, tuple[str, str]]:
    snippet = function_body_snippet(text, func_name)
    if not snippet:
        return {}
    hints: dict[int, tuple[str, str]] = function_decl_arg_hints(text, func_name)

    arg_array = r"(?:args|all_args|pos_args)"
    patterns = [
        re.compile(r"(?P<name>[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z_][A-Za-z0-9_]*)\s*(?<![=!<>])=(?!=)\s*(?P<expr>[^;\n]*?" + arg_array + r"\[(?P<idx>\d+)\][^;\n]*)"),
        re.compile(r"(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*(?<![=!<>])=(?!=)\s*(?P<expr>[^;\n]*?" + arg_array + r"\[(?P<idx>\d+)\][^;\n]*)"),
    ]
    for pattern in patterns:
        for match in pattern.finditer(snippet):
            idx = int(match.group("idx"))
            raw_name = match.group("name")
            expr = match.groupdict().get("expr") or ""
            candidate = (normalize_arg_name(raw_name), converter_arg_type(expr))
            hints[idx] = prefer_arg_hint(hints.get(idx), candidate)

    # py_helper_consume_array lets callers pass a tuple/list or expanded positional values.
    vectors: dict[str, tuple[int, int]] = {}
    consume_re = re.compile(
        r"py_helper_consume_array\s*\(\s*n_args\s*,\s*args\s*,\s*(?P<start>\d+)\s*,\s*(?P<count>\d+)\s*,\s*&(?P<vec>[A-Za-z_][A-Za-z0-9_]*)"
    )
    for match in consume_re.finditer(snippet):
        vectors[match.group("vec")] = (int(match.group("start")), int(match.group("count")))
    for vec, (start, count) in vectors.items():
        vec_re = re.compile(
            r"(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*(?<![=!<>])=(?!=)\s*(?P<expr>[^;\n]*?" + re.escape(vec) + r"\[(?P<idx>\d+)\][^;\n]*)"
        )
        for match in vec_re.finditer(snippet):
            vec_idx = int(match.group("idx"))
            if vec_idx >= count:
                continue
            idx = start + vec_idx
            candidate = (normalize_arg_name(match.group("name")), converter_arg_type(match.group("expr")))
            hints[idx] = prefer_arg_hint(hints.get(idx), candidate)

    # Infer names from helper calls that pass args[i] into a named output field.
    helper_re = re.compile(
        r"[A-Za-z_][A-Za-z0-9_]*\s*\(\s*" + arg_array + r"\[(?P<idx>\d+)\]\s*,\s*&?(?P<target>[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)?)"
    )
    for match in helper_re.finditer(snippet):
        target = match.group("target")
        if target in {"bufinfo", "len", "items_count", "vstr.len"}:
            continue
        idx = int(match.group("idx"))
        candidate = (normalize_arg_name(target), "Any")
        hints[idx] = prefer_arg_hint(hints.get(idx), candidate)

    array_re = re.compile(
        r"mp_obj_get_array(?:_fixed_n)?\s*\(\s*" + arg_array + r"\[(?P<idx>\d+)\]\s*,[^;]*&(?P<target>[A-Za-z_][A-Za-z0-9_]*)"
    )
    for match in array_re.finditer(snippet):
        idx = int(match.group("idx"))
        candidate = (normalize_arg_name(match.group("target")), "Any")
        hints[idx] = prefer_arg_hint(hints.get(idx), candidate)

    roi_re = re.compile(r"py_helper_keyword_rectangle_roi\s*\([^,]+,\s*n_args\s*,\s*args\s*,\s*(?P<idx>\d+)")
    for match in roi_re.finditer(snippet):
        idx = int(match.group("idx"))
        hints[idx] = prefer_arg_hint(hints.get(idx), ("roi", "Any"))

    buffer_re = re.compile(r"mp_get_buffer(?:_raise)?\s*\(\s*" + arg_array + r"\[(?P<idx>\d+)\]")
    for match in buffer_re.finditer(snippet):
        idx = int(match.group("idx"))
        hints[idx] = prefer_arg_hint(hints.get(idx), ("buf", "Any"))

    if func_name.endswith("read") and "vstr_init_len" in snippet:
        hints[1] = prefer_arg_hint(hints.get(1), ("nbytes", "int"))
    if func_name.endswith(("read", "readinto")) and re.search(r"memset\s*\([^;]*args\[2\]", snippet, re.DOTALL):
        hints[2] = prefer_arg_hint(hints.get(2), ("write", "int"))

    # Fall back to a neutral name for direct unassigned args[i] usage.
    used_indexes = {int(idx) for idx in re.findall(arg_array + r"\[(\d+)\]", snippet)}
    for idx in used_indexes:
        hints.setdefault(idx, (f"arg{idx}", "Any"))
    return hints


def infer_min_args_hint(text: str, func_name: str) -> int | None:
    snippet = function_body_snippet(text, func_name)
    if not snippet:
        return None
    max_required: int | None = None
    consume_re = re.compile(
        r"py_helper_consume_array\s*\(\s*n_args\s*,\s*args\s*,\s*(?P<start>\d+)\s*,\s*(?P<count>\d+)"
    )
    for match in consume_re.finditer(snippet):
        required = int(match.group("start")) + int(match.group("count"))
        max_required = required if max_required is None else max(max_required, required)
    return max_required


def helper_kw_type(helper: str) -> str:
    if helper.endswith(("_int", "_int_maybe")):
        return "int"
    if helper.endswith(("_float", "_float_maybe")):
        return "float"
    if helper.endswith("_color") or helper.endswith("_color_palette") or helper.endswith("_alpha_palette"):
        return "Any"
    return "Any"


def infer_kw_hints(text: str, func_name: str, seen: set[str] | None = None) -> list[str]:
    seen = set(seen or set())
    if func_name in seen:
        return []
    seen.add(func_name)
    snippet = function_body_snippet(text, func_name)
    if not snippet:
        return []
    hints: list[str] = []
    seen: set[str] = set()

    def add(name: str, typ: str) -> None:
        name = normalize_arg_name(name)
        if name in seen or name.startswith("arg"):
            return
        seen.add(name)
        hints.append(f"{name}: {typ} = ...")

    named_re = re.compile(
        r"(?P<helper>py_helper_keyword_[A-Za-z0-9_]+)\s*\([^;]*?MP_(?:OBJ_NEW_)?QSTR\(\s*MP_QSTR_(?P<name>[A-Za-z0-9_]+)\s*\)",
        re.DOTALL,
    )
    for match in named_re.finditer(snippet):
        add(match.group("name"), helper_kw_type(match.group("helper")))

    if "py_helper_keyword_color" in snippet:
        add("color", "Any")
    if "py_helper_keyword_rectangle_roi" in snippet:
        add("roi", "Any")
    if "py_helper_keyword_to_image_mutable_mask" in snippet:
        add("mask", "Any")
    if "py_helper_keyword_thresholds" in snippet:
        add("thresholds", "Any")
    if hints:
        return hints

    wrapper_re = re.compile(
        r"(?:return\s+)?(?P<helper>[A-Za-z_][A-Za-z0-9_]*)\s*\([^;{]*?n_args\s*,\s*args\s*,\s*kw_args\s*\)",
        re.DOTALL,
    )
    for match in wrapper_re.finditer(snippet):
        helper = match.group("helper")
        if helper == func_name or helper.startswith("py_helper_"):
            continue
        delegated = infer_kw_hints(text, helper, seen)
        if delegated:
            return delegated
    return hints


def function_body_snippet(text: str, func_name: str, limit: int = 7000) -> str:
    pattern = re.compile(r"(?:STATIC\s+|static\s+)?(?:mp_obj_t|void|int|bool|STATIC\s+mp_obj_t)\s+" + re.escape(func_name) + r"\s*\([^;]*?\)\s*\{", re.DOTALL)
    match = pattern.search(text)
    if not match:
        pos = text.find(func_name + "(")
        return text[pos:pos + limit] if pos >= 0 else ""

    start = match.start()
    open_brace = text.find("{", match.start())
    depth = 0
    for index in range(open_brace, min(len(text), open_brace + limit)):
        ch = text[index]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[start:index + 1]
    return text[start:start + limit]


def parse_arg_table_body(text: str, table_name: str) -> str | None:
    table_name_re = re.escape(table_name)
    patterns = [
        rf"{table_name_re}\s*\[\]\s*=\s*\{{(?P<body>.*?)\}};",
        rf"mp_arg_t\s+{table_name_re}\s*\[\]\s*=\s*\{{(?P<body>.*?)\}};",
    ]
    for pattern in patterns:
        match = re.search(pattern, text, re.DOTALL)
        if match:
            return match.group("body")
    return None


def parse_arg_entries(body: str) -> list[str]:
    args: list[str] = []
    for entry in ARG_ENTRY_RE.finditer(strip_c_comments(body)):
        name = entry.group("name")
        flags = entry.group("flags")
        field = entry.group("field")
        arg = f"{name}: {arg_type(flags, field)}"
        if "MP_ARG_REQUIRED" not in flags:
            arg += f" = {parse_default(field, entry.group('default'))}"
        if "MP_ARG_KW_ONLY" in flags and "*" not in args:
            args.append("*")
        args.append(arg)
    return args


def parse_allowed_args(text: str, func_name: str) -> list[str]:
    snippet = function_body_snippet(text, func_name)
    if not snippet:
        return []
    body = parse_arg_table_body(snippet, "allowed_args")
    if body is not None:
        return parse_arg_entries(body)

    parse_match = re.search(
        r"mp_arg_parse_all(?:_kw_array)?\s*\([^;]*?,\s*(?P<table>[A-Za-z_][A-Za-z0-9_]*)\s*,\s*(?:args|vals)\s*\)",
        snippet,
        re.DOTALL,
    )
    if parse_match:
        body = parse_arg_table_body(text, parse_match.group("table"))
        if body is not None:
            return parse_arg_entries(body)
    return []


def c_default(value: str) -> str:
    value = value.strip()
    if value in {"true", "false"}:
        return "True" if value == "true" else "False"
    if value == "mp_const_none":
        return "None"
    if re.fullmatch(r"-?0x[0-9A-Fa-f]+|-?[0-9]+", value):
        return value
    return "..."


def infer_map_lookup_args(text: str, func_name: str) -> list[str]:
    snippet = function_body_snippet(text, func_name)
    if not snippet or "mp_map_lookup" not in snippet:
        return []
    args: list[str] = []
    seen: set[str] = set()
    pattern = re.compile(
        r"mp_map_lookup\([^;]*MP_QSTR_(?P<name>[A-Za-z0-9_]+)[^;]*\)\s*;\s*"
        r"(?P<assign>[^;]*?=\s*elem\s*\?\s*(?P<expr>[^:;]+)\s*:\s*(?P<default>[^;]+);)",
        re.DOTALL,
    )
    for match in pattern.finditer(snippet):
        name = normalize_arg_name(match.group("name"))
        if name in seen:
            continue
        seen.add(name)
        typ = converter_arg_type(match.group("expr"))
        args.append(f"{name}: {typ} = {c_default(match.group('default'))}")
    for match in re.finditer(r"mp_map_lookup\([^;]*MP_QSTR_(?P<name>[A-Za-z0-9_]+)", snippet):
        name = normalize_arg_name(match.group("name"))
        if name in seen:
            continue
        seen.add(name)
        args.append(f"{name}: Any = ...")
    return args


def delegated_allowed_args(text: str, func_name: str) -> tuple[int, list[str]] | None:
    snippet = function_body_snippet(text, func_name)
    if not snippet:
        return None
    call_re = re.compile(
        r"(?P<helper>[A-Za-z_][A-Za-z0-9_]*)\s*\([^;]*?"
        r"n_args(?:\s*-\s*(?P<offset>\d+))?\s*,\s*"
        r"(?:(?:args|all_args|pos_args)(?:\s*\+\s*(?P<ptr_offset>\d+))?)[^;]*?kw_args",
        re.DOTALL,
    )
    for match in call_re.finditer(snippet):
        helper = match.group("helper")
        if helper == func_name:
            continue
        helper_args = parse_allowed_args(text, helper)
        if not helper_args:
            continue
        offset = int(match.group("offset") or match.group("ptr_offset") or 0)
        return offset, helper_args
    return None


def require_first_args(args: list[str], count: int) -> list[str]:
    if count <= 0:
        return args
    result: list[str] = []
    required_seen = 0
    for arg in args:
        if arg == "*" or arg.startswith("**") or arg.startswith("*"):
            result.append(arg)
            continue
        if required_seen < count and " = " in arg:
            arg = arg.split(" = ", 1)[0]
        required_seen += 1
        result.append(arg)
    return result


def infer_init_args(text: str, func_name: str) -> list[str]:
    init_args = parse_allowed_args(text, func_name)
    if init_args:
        return init_args

    checked = parse_arg_check_num(text, func_name)
    if not checked:
        return []
    min_args, max_args, accepts_kw = checked
    init_hints = infer_arg_hints(text, func_name)
    min_hint = infer_min_args_hint(text, func_name)
    if min_hint is not None:
        min_args = max(min_args, min_hint)

    delegated = delegated_allowed_args(text, func_name)
    if delegated:
        offset, helper_args = delegated
        base_args = args_from_arity(offset, offset, include_self=False, accepts_kw=False, positional_only=True, arg_hints=init_hints)
        helper_args = require_first_args(helper_args, max(min_args - offset, 0))
        args = base_args + helper_args
        map_args = infer_map_lookup_args(text, func_name)
        if map_args:
            args = add_kw_hints(args, map_args)
        return args

    map_args = infer_map_lookup_args(text, func_name)
    if map_args:
        args = args_from_arity(min_args, min_args, include_self=False, accepts_kw=False, positional_only=True, arg_hints=init_hints)
        return add_kw_hints(args, map_args)

    return args_from_arity(min_args, max_args, include_self=False, accepts_kw=accepts_kw, positional_only=not accepts_kw, arg_hints=init_hints)


def parse_arg_check_num(text: str, func_name: str) -> tuple[int, int | None, bool] | None:
    snippet = function_body_snippet(text, func_name, 1600)
    if not snippet:
        return None
    match = MP_ARG_CHECK_RE.search(snippet)
    if not match:
        return None
    min_args = int(match.group("min"))
    max_raw = match.group("max")
    max_args = None if max_raw == "MP_OBJ_FUN_ARGS_MAX" else int(max_raw)
    return min_args, max_args, match.group("kw") == "true"


def args_from_arity(
    min_args: int,
    max_args: int | None,
    *,
    include_self: bool,
    accepts_kw: bool,
    positional_only: bool = False,
    arg_hints: dict[int, tuple[str, str]] | None = None,
) -> list[str]:
    arg_hints = arg_hints or {}
    consumed_self = 1 if include_self else 0
    required = max(min_args - consumed_self, 0)
    max_user = None if max_args is None else max(max_args - consumed_self, 0)
    optional = 0 if max_user is None else max(max_user - required, 0)
    parts = ["self"] if include_self else []
    used_names = {"self"} if include_self else set()

    def arg_part(user_index: int, optional_arg: bool) -> str:
        c_index = user_index + consumed_self
        name, typ = arg_hints.get(c_index, (f"arg{user_index}", "Any"))
        name = normalize_arg_name(name)
        if name in used_names:
            name = f"{name}_{user_index}"
        used_names.add(name)
        text = f"{name}: {typ or 'Any'}"
        if optional_arg:
            text += " = ..."
        return text

    for index in range(required):
        parts.append(arg_part(index, False))
    for index in range(optional):
        parts.append(arg_part(required + index, True))
    if positional_only and any(not part.startswith("*") for part in parts):
        parts.append("/")
    if max_user is None and not accepts_kw:
        parts.append("*args: Any")
    if accepts_kw:
        parts.append("**kwargs: Any")
    return parts


def signature_from_args(args: list[str], return_type: str = "Any") -> str:
    return "(" + ", ".join(args) + f") -> {return_type}"


def infer_return_type(name: str) -> str:
    if name in {"close", "deinit", "init", "update", "reset", "flush", "sendbreak"}:
        return "None"
    if name.startswith(("is_", "get_")):
        return "Any"
    if name in {"digest", "read", "readline"}:
        return "bytes"
    if name in {"write", "readinto", "any"}:
        return "int"
    return "Any"


COMMON_SIGNATURE_NAMES = {
    "readfrom": ["addr", "nbytes", "stop"],
    "readfrom_into": ["addr", "buf", "stop"],
    "readinto": ["buf", "nack"],
    "writeto": ["addr", "buf", "stop"],
    "writevto": ["addr", "vector", "stop"],
    "readfrom_mem": ["addr", "mem_addr", "nbytes", "addrsize"],
    "readfrom_mem_into": ["addr", "mem_addr", "buf", "addrsize"],
    "writeto_mem": ["addr", "mem_addr", "buf", "addrsize"],
    "get": ["key", "default"],
    "pop": ["key", "default"],
    "setdefault": ["key", "default"],
    "start": ["group"],
    "end": ["group"],
    "span": ["group"],
    "makefile": ["mode", "buffering"],
    "encrypt": ["input", "output"],
    "decrypt": ["input", "output"],
    "enable": ["enable"],
    "datetime": ["date"],
    "save_wav": ["wav_list", "wav_length", "wav_path", "sample_rate"],
    "body_seg_postprocess": ["data_mp", "num_class", "ori_shape_mp", "dst_shape_mp", "color"],
}


def apply_common_arg_names(args: list[str], func_name: str | None, include_self: bool) -> list[str]:
    if not func_name:
        return args
    names = COMMON_SIGNATURE_NAMES.get(func_name)
    if not names:
        return args
    result = list(args)
    start = 1 if include_self and result and result[0] == "self" else 0
    for offset, name in enumerate(names):
        index = start + offset
        if index >= len(result):
            break
        part = result[index]
        if part.startswith("*args") or part.startswith("**kwargs") or ":" not in part:
            continue
        current, rest = part.split(":", 1)
        if re.fullmatch(r"arg\d*", current.strip()):
            result[index] = f"{name}:{rest}"
    return result


def add_kw_hints(args: list[str], kw_hints: list[str]) -> list[str]:
    if not kw_hints:
        return args
    result = [arg for arg in args if arg != "**kwargs: Any"]
    used_names = {part.split(":", 1)[0].strip() for part in result if ":" in part}
    filtered = [hint for hint in kw_hints if hint.split(":", 1)[0].strip() not in used_names]
    if not filtered:
        return result
    if "*" not in result:
        result.append("*")
    result.extend(filtered)
    return result


def function_signature(func: CFunction, *, include_self: bool, name: str | None = None) -> str:
    func_name = name or func.obj
    if func.allowed_args:
        args = (["self"] if include_self else []) + func.allowed_args
        args = add_kw_hints(args, func.kw_hints)
        args = apply_common_arg_names(args, func_name, include_self)
        return signature_from_args(args, infer_return_type(func_name))
    if func.min_args is not None:
        min_args = max(func.min_args, func.min_args_hint or 0)
        args = args_from_arity(min_args, func.max_args, include_self=include_self, accepts_kw=func.accepts_kw, positional_only=func.positional_only, arg_hints=func.arg_hints)
        args = add_kw_hints(args, func.kw_hints)
        args = apply_common_arg_names(args, func_name, include_self)
        return signature_from_args(args, infer_return_type(func_name))
    return "(self, *args: Any, **kwargs: Any) -> Any" if include_self else "(*args: Any, **kwargs: Any) -> Any"


STREAM_METHOD_SIGNATURES = {
    "mp_stream_read": "(self, nbytes: Optional[int] = None) -> bytes",
    "mp_stream_readinto": "(self, buf: Any, nbytes: Optional[int] = None) -> int",
    "mp_stream_unbuffered_readline": "(self) -> bytes",
    "mp_stream_write": "(self, buf: Any) -> int",
}


def stream_method_signature(obj: str) -> str | None:
    return STREAM_METHOD_SIGNATURES.get(obj)


def function_uses_kw_args(text: str, func_name: str) -> bool:
    snippet = function_body_snippet(text, func_name)
    if not snippet:
        return False
    open_brace = snippet.find("{")
    body = snippet[open_brace + 1:] if open_brace >= 0 else snippet
    body = re.sub(r"\(\s*void\s*\)\s*kw_args\s*;", "", body)
    return "kw_args" in body


def collect_functions(text: str) -> dict[str, CFunction]:
    functions: dict[str, CFunction] = {}
    for match in FUN_OBJ_FIXED_RE.finditer(text):
        argc = int(match.group("argc"))
        obj = match.group("obj")
        functions[obj] = CFunction(obj=obj, func=match.group("func"), min_args=argc, max_args=argc)
    for match in FUN_OBJ_VAR_RE.finditer(text):
        obj = match.group("obj")
        max_group = match.group("max")
        functions[obj] = CFunction(
            obj=obj,
            func=match.group("func"),
            min_args=int(match.group("min")),
            max_args=int(max_group) if max_group is not None else None,
        )
    for match in FUN_OBJ_KW_RE.finditer(text):
        obj = match.group("obj")
        functions[obj] = CFunction(obj=obj, func=match.group("func"), min_args=int(match.group("min")), max_args=None, accepts_kw=True)

    for match in STATICMETHOD_OBJ_RE.finditer(text):
        alias = match.group("alias")
        target = match.group("target")
        target_obj = target[:-4] if target.endswith("_obj") else target
        base = functions.get(target_obj)
        if base is not None:
            functions[alias] = CFunction(
                obj=alias,
                func=base.func,
                min_args=base.min_args,
                max_args=base.max_args,
                accepts_kw=base.accepts_kw,
                positional_only=base.positional_only,
                is_staticmethod=True,
            )

    for fn in functions.values():
        fn.allowed_args = parse_allowed_args(text, fn.func)
        if not fn.allowed_args:
            delegated = delegated_allowed_args(text, fn.func)
            if delegated:
                fn.allowed_args = delegated[1]
        fn.arg_hints = infer_arg_hints(text, fn.func)
        fn.min_args_hint = infer_min_args_hint(text, fn.func)
        fn.kw_hints = infer_kw_hints(text, fn.func)
        checked = parse_arg_check_num(text, fn.func)
        if checked and not fn.allowed_args:
            fn.min_args, fn.max_args, fn.accepts_kw = checked
        if not fn.allowed_args and fn.accepts_kw and not function_uses_kw_args(text, fn.func):
            fn.accepts_kw = False
            fn.positional_only = True
        elif not fn.accepts_kw:
            fn.positional_only = True
    return functions


def locals_dict_from_body(body: str) -> str | None:
    match = re.search(r"locals_dict\s*,\s*&(?P<dict>[A-Za-z0-9_]+)", body)
    return match.group("dict") if match else None


def make_new_from_body(body: str) -> str | None:
    match = re.search(r"make_new\s*,\s*(?P<func>[A-Za-z0-9_]+)", body)
    return match.group("func") if match else None


def globals_dict_from_module_body(body: str) -> str | None:
    match = re.search(r"\.globals\s*=\s*\([^)]*\)\s*&(?P<dict>[A-Za-z0-9_]+)", body)
    if not match:
        match = re.search(r"globals\s*=\s*\([^)]*\)\s*&(?P<dict>[A-Za-z0-9_]+)", body)
    return match.group("dict") if match else None


def analyze_c_sources(sources: Iterable[Path]) -> CAnalysis:
    analysis = CAnalysis(sources=sorted(set(sources)))
    source_text: dict[Path, str] = {}
    c_macros: dict[str, str] = {}

    for src in analysis.sources:
        text = src.read_text(errors="ignore")
        source_text[src] = text
        c_macros.update(collect_c_macros(text))
        # Also collect macros from locally-included headers so that table-body
        # macros like OPENCV_CORE_GLOBALS can be expanded.
        c_macros.update(resolve_local_includes(src))
        for match in ROM_MAP_RE.finditer(text):
            body = expand_table_body_macros(match.group("body"), c_macros)
            analysis.table_bodies[match.group("name")] = body
        for match in CONST_DICT_RE.finditer(text):
            analysis.dict_tables[match.group("dict")] = match.group("table")
        analysis.functions.update(collect_functions(text))

    for src, text in source_text.items():
        for match in TYPE_RE.finditer(text):
            type_var = match.group("type")
            body = match.group("body")
            ctype = CType(
                type_var=type_var,
                qstr=match.group("qstr"),
                make_new=make_new_from_body(body),
                locals_dict=locals_dict_from_body(body),
            )
            if ctype.make_new:
                ctype.init_args = infer_init_args(text, ctype.make_new)
            analysis.types[type_var] = ctype

        for match in MODULE_DEF_RE.finditer(text):
            module_var = match.group("var")
            globals_dict = globals_dict_from_module_body(match.group("body"))
            for register in REGISTER_RE.finditer(text):
                if register.group("var") == module_var:
                    module_name = qstr_module_name(register.group("module"))
                    analysis.modules[module_name] = CModule(
                        name=module_name,
                        var=module_var,
                        globals_dict=globals_dict,
                        table=analysis.dict_tables.get(globals_dict or ""),
                        source=str(src),
                    )

    network_interfaces = expand_c_macro("MICROPY_PORT_NETWORK_INTERFACES", c_macros)
    if network_interfaces:
        analysis.module_extra_bodies["network"] = network_interfaces

    for ctype in analysis.types.values():
        if not ctype.locals_dict:
            continue
        table = analysis.dict_tables.get(ctype.locals_dict)
        body = analysis.table_bodies.get(table or "", "")
        for entry in ENTRY_RE.finditer(body):
            name = entry.group("name")
            if name == "__del__" or not valid_stub_identifier(name):
                continue
            rhs = entry.group("rhs")
            ptr = PTR_RE.search(rhs)
            if ptr:
                var = ptr.group("var")
                obj = var[:-4] if var.endswith("_obj") else var
                if obj == "py_func_unavailable" and name in ctype.methods:
                    continue
                func = analysis.functions.get(obj)
                if func is None:
                    if "MP_ROM_INT" in rhs or name.isupper():
                        ctype.attrs[name] = "int"
                    continue
                signature = stream_method_signature(obj)
                if signature is None:
                    signature = function_signature(func, include_self=not func.is_staticmethod, name=name)
                current = ctype.methods.get(name)
                generic_self = "(self, *args: Any, **kwargs: Any) -> Any"
                generic_static = "(*args: Any, **kwargs: Any) -> Any"
                if current is None or current in {generic_self, generic_static} or obj != "py_func_unavailable":
                    ctype.methods[name] = signature
            elif "MP_ROM_INT" in rhs or name.isupper():
                ctype.attrs[name] = "int"

        # Synthesize dunder methods from MicroPython type slots.
        _apply_type_slot_methods(ctype, analysis)

    return analysis


_SLOT_DUNDER_METHODS: dict[str, list[tuple[str, str]]] = {
    "binary_op": [
        ("__add__", "(self, other: Any, /) -> ndarray"),
        ("__sub__", "(self, other: Any, /) -> ndarray"),
        ("__mul__", "(self, other: Any, /) -> ndarray"),
        ("__truediv__", "(self, other: Any, /) -> ndarray"),
        ("__floordiv__", "(self, other: Any, /) -> ndarray"),
        ("__mod__", "(self, other: Any, /) -> ndarray"),
        ("__pow__", "(self, other: Any, /) -> ndarray"),
        ("__lshift__", "(self, other: Any, /) -> ndarray"),
        ("__rshift__", "(self, other: Any, /) -> ndarray"),
        ("__and__", "(self, other: Any, /) -> ndarray"),
        ("__or__", "(self, other: Any, /) -> ndarray"),
        ("__xor__", "(self, other: Any, /) -> ndarray"),
        ("__lt__", "(self, other: Any, /) -> ndarray"),
        ("__le__", "(self, other: Any, /) -> ndarray"),
        ("__gt__", "(self, other: Any, /) -> ndarray"),
        ("__ge__", "(self, other: Any, /) -> ndarray"),
        ("__eq__", "(self, other: Any, /) -> ndarray"),
        ("__ne__", "(self, other: Any, /) -> ndarray"),
    ],
    "unary_op": [
        ("__neg__", "(self, /) -> ndarray"),
        ("__pos__", "(self, /) -> ndarray"),
        ("__abs__", "(self, /) -> ndarray"),
        ("__invert__", "(self, /) -> ndarray"),
    ],
    "subscr": [
        ("__getitem__", "(self, index: Any, /) -> Any"),
        ("__setitem__", "(self, index: Any, value: Any, /) -> None"),
    ],
    "iter": [
        ("__iter__", "(self, /) -> Any"),
        ("__next__", "(self, /) -> Any"),
    ],
    "len": [
        ("__len__", "(self, /) -> int"),
    ],
}


def _apply_type_slot_methods(ctype: CType, analysis: CAnalysis) -> None:
    """Add dunder methods implied by MicroPython type slots.

    Slots like ``binary_op``, ``unary_op``, ``subscr``, ``iter`` and ``len``
    are not listed in the type's locals dictionary but still define
    user-visible Python behaviour.  We detect them by inspecting the
    ``MP_DEFINE_CONST_OBJ_TYPE`` body stored in *analysis*.

    Slot-based dunder methods are only synthesised for types whose source
    file lives inside the ulab tree, because those are the only types where
    we can confidently map slots to the full set of numeric operators.
    """
    # Locate the TYPE_RE body that defines this type.
    type_body: str | None = None
    type_source: Path | None = None
    for src in analysis.sources:
        try:
            text = src.read_text(errors="ignore")
        except OSError:
            continue
        for match in TYPE_RE.finditer(text):
            if match.group("type") == ctype.type_var:
                type_body = match.group("body")
                type_source = src
                break
        if type_body is not None:
            break
    if type_body is None:
        return

    # Expand macros so that slot macros like NDARRAY_TYPE_BINARY_OP
    # (which expand to "binary_op, ndarray_binary_op,") are resolved.
    macros: dict[str, str] = {}
    if type_source is not None:
        try:
            macros.update(collect_c_macros(type_source.read_text(errors="ignore")))
        except OSError:
            pass
        macros.update(resolve_local_includes(type_source))
    if macros:
        type_body = expand_table_body_macros(type_body, macros)

    # Only synthesise full arithmetic operators for ulab-owned types.
    _is_ulab = type_source is not None and "ulab" in str(type_source)

    for slot, methods in _SLOT_DUNDER_METHODS.items():
        if re.search(r"\b" + re.escape(slot) + r"\s*,", type_body):
            for method_name, signature in methods:
                if method_name not in ctype.methods:
                    if not _is_ulab:
                        # For non-ulab types only emit comparison operators
                        # and container protocols; skip arithmetic.
                        if slot == "binary_op" and method_name not in _COMPARISON_DUNDER_NAMES:
                            continue
                        if slot == "unary_op":
                            continue
                        # Use generic return types for non-ulab types.
                        signature = _genericise_signature(signature)
                    ctype.methods[method_name] = signature

    # attr slot: scan the attr handler function for MP_QSTR_ property names.
    if _is_ulab:
        _apply_attr_slot_properties(ctype, type_body, type_source, analysis)


_COMPARISON_DUNDER_NAMES = {
    "__eq__", "__ne__", "__lt__", "__le__", "__gt__", "__ge__",
}


def _genericise_signature(signature: str) -> str:
    """Replace ndarray-specific return types with ``Any``."""
    return signature.replace(" -> ndarray", " -> Any")


_ATTR_SLOT_RE = re.compile(r"attr\s*,\s*(?P<func>[A-Za-z_][A-Za-z0-9_]*)")
_ATTR_QSTR_RE = re.compile(r"case\s+MP_QSTR_(?P<name>[A-Za-z0-9_]+)\s*:")


def _apply_attr_slot_properties(
    ctype: CType, type_body: str, type_source: Path | None, analysis: CAnalysis
) -> None:
    """Detect an ``attr`` slot and extract property names from its handler."""
    attr_match = _ATTR_SLOT_RE.search(type_body)
    if not attr_match or type_source is None:
        return
    func_name = attr_match.group("func")
    # Find the handler function body in the source tree.
    func_text = _find_function_body(func_name, analysis)
    if not func_text:
        return
    for match in _ATTR_QSTR_RE.finditer(func_text):
        prop_name = match.group("name")
        if prop_name.startswith("_"):
            continue
        if valid_stub_identifier(prop_name) and prop_name not in ctype.attrs:
            # Attempt to guess the type from the handler call
            ctype.attrs[prop_name] = "Any"


def _find_function_body(func_name: str, analysis: CAnalysis) -> str:
    """Search all source files for a function definition and return its body."""
    pattern = re.compile(
        r"(?:void|STATIC\s+void|static\s+void|mp_obj_t|STATIC\s+mp_obj_t|static\s+mp_obj_t)\s+"
        + re.escape(func_name)
        + r"\s*\([^)]*\)\s*\{",
        re.DOTALL,
    )
    for src in analysis.sources:
        try:
            text = src.read_text(errors="ignore")
        except OSError:
            continue
        match = pattern.search(text)
        if match:
            start = match.start()
            body_start = text.find("{", match.start())
            if body_start >= 0:
                depth = 0
                for i in range(body_start, min(len(text), body_start + 8000)):
                    if text[i] == "{":
                        depth += 1
                    elif text[i] == "}":
                        depth -= 1
                        if depth == 0:
                            return text[start : i + 1]
    return ""


ENTRY_KIND_PRIORITY = {"object": 0, "const": 1, "function": 2, "class": 3}


def prefer_entry(current: tuple[str, str | None] | None, candidate: tuple[str, str | None]) -> tuple[str, str | None]:
    if current is None:
        return candidate
    current_kind, current_ref = current
    candidate_kind, candidate_ref = candidate
    if current_ref == "py_func_unavailable_obj" and candidate_ref != "py_func_unavailable_obj":
        return candidate
    if candidate_ref == "py_func_unavailable_obj" and current_ref != "py_func_unavailable_obj":
        return current
    if ENTRY_KIND_PRIORITY.get(candidate_kind, 0) > ENTRY_KIND_PRIORITY.get(current_kind, 0):
        return candidate
    return current


def module_entries(analysis: CAnalysis, module: CModule) -> dict[str, tuple[str, str | None]]:
    entries: dict[str, tuple[str, str | None]] = {}
    body = analysis.table_bodies.get(module.table or "", "")
    extra_body = analysis.module_extra_bodies.get(module.name, "")
    if extra_body:
        body += "\n" + extra_body
    for entry in ENTRY_RE.finditer(body):
        name = entry.group("name")
        if name == "__name__" or name.startswith("_dot_") or not valid_stub_identifier(name):
            continue
        rhs = entry.group("rhs")
        ptr = PTR_RE.search(rhs)
        if ptr:
            var = ptr.group("var")
            if var in analysis.types:
                candidate = ("class", var)
            elif var.endswith("_obj") and var[:-4] in analysis.functions:
                candidate = ("function", var[:-4])
            else:
                candidate = ("object", var)
        elif "MP_ROM_INT" in rhs or "MP_OBJ_NEW_QSTR" in rhs or name.isupper():
            candidate = ("const", None)
        else:
            candidate = ("object", None)
        entries[name] = prefer_entry(entries.get(name), candidate)
    return entries


def types_by_qstr(analysis: CAnalysis) -> dict[str, CType]:
    result: dict[str, CType] = {}
    for ctype in analysis.types.values():
        existing = result.get(ctype.qstr)
        if existing is None or len(ctype.methods) > len(existing.methods):
            result[ctype.qstr] = ctype
    return result


def render_ctype_class(name: str, ctype: CType, override: dict[str, Any]) -> list[str]:
    methods = dict(ctype.methods)
    if ctype.make_new is not None:
        methods["__init__"] = signature_from_args(["self"] + ctype.init_args, "None")
    return render_class(name, override, methods, ctype.attrs, add_default_init=ctype.make_new is not None)


def module_stub_path(out_dir: Path, module_name: str, package_modules: set[str]) -> Path:
    rel = Path(*module_name.split("."))
    if module_name in package_modules:
        return out_dir / rel / "__init__.pyi"
    return out_dir / rel.with_suffix(".pyi")


def _module_is_extensible(module: CModule, analysis: CAnalysis) -> bool:
    """Return True when *module* is an extensible module whose functions behave
    like methods on a singleton instance (e.g. ``kpu``).  In that case the first
    C-level parameter is the bound module itself and should be hidden in stubs.
    """
    if not module.globals_dict:
        return False
    for ctype in analysis.types.values():
        if ctype.qstr == module.name and ctype.locals_dict == module.globals_dict:
            return True
    return False


def generate_c_module_stub(module_name: str, module: CModule, analysis: CAnalysis, out_dir: Path, overrides: OverrideMap, package_modules: set[str]) -> bool:
    entries = module_entries(analysis, module)
    symbols = module_symbols(overrides, module_name)
    qstr_types = types_by_qstr(analysis)
    for name, override in symbols.items():
        if isinstance(override, dict):
            entries.setdefault(name, (override.get("kind", "function"), None))
    if not entries:
        return False

    module_is_extensible = _module_is_extensible(module, analysis)
    module_doc = module_override(overrides, module_name).get("doc")
    lines = [HEADER.rstrip(), ""]
    lines.extend(doc_lines(module_doc, ""))
    if module_doc:
        lines.append("")
    for name, (kind, ref) in sorted(entries.items()):
        override = symbols.get(name, {})
        override = override if isinstance(override, dict) else {}
        factory_type = qstr_types.get(name) if kind in {"function", "object"} else None
        if kind == "class" and ref in analysis.types:
            lines.extend(render_ctype_class(name, analysis.types[ref], override))
        elif factory_type is not None:
            lines.extend(render_ctype_class(name, factory_type, override))
        elif override.get("kind"):
            lines.extend(render_override_symbol(name, override))
        elif kind == "function" and ref in analysis.functions:
            lines.extend(render_function(name, function_signature(analysis.functions[ref], include_self=module_is_extensible, name=name), override.get("doc")))
        elif kind == "const":
            lines.append(f"{name}: {override.get('type', 'Any')}")
        else:
            lines.append(f"{name}: Any")
    dst = module_stub_path(out_dir, module_name, package_modules)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return True


def ensure_c_parent_packages(out_dir: Path, module_names: set[str]) -> None:
    children: dict[str, set[str]] = {}
    for module_name in module_names:
        parts = module_name.split(".")
        for index in range(1, len(parts)):
            parent = ".".join(parts[:index])
            children.setdefault(parent, set()).add(parts[index])

    for parent, child_names in sorted(children.items()):
        init_path = out_dir / Path(*parent.split(".")) / "__init__.pyi"
        if init_path.exists():
            continue
        init_path.parent.mkdir(parents=True, exist_ok=True)
        lines = [HEADER.rstrip(), ""]
        for child in sorted(child_names):
            if valid_stub_identifier(child):
                lines.append(f"from . import {child} as {child}")
        if len(lines) == 2:
            lines.append("...")
        init_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def generate_c_module_stubs(out_dir: Path, overrides: OverrideMap, analysis: CAnalysis) -> int:
    count = 0
    module_names = set(analysis.modules)
    package_modules = {name for name in module_names if any(other.startswith(name + ".") for other in module_names)}
    for module_name, module in sorted(analysis.modules.items()):
        if generate_c_module_stub(module_name, module, analysis, out_dir, overrides, package_modules):
            count += 1
    ensure_c_parent_packages(out_dir, module_names)
    return count


def copy_resource_libs(out_dir: Path) -> int:
    if not RESOURCE_LIBS_DIR.exists():
        return 0
    dst_root = out_dir / "libs"
    dst_root.mkdir(parents=True, exist_ok=True)
    init_file = dst_root / "__init__.py"
    if not init_file.exists():
        init_file.write_text("# CanMV resources/libs package for IDE analysis.\n", encoding="utf-8")

    count = 0
    for src in sorted(RESOURCE_LIBS_DIR.rglob("*.py")):
        rel = src.relative_to(RESOURCE_LIBS_DIR)
        dst = dst_root / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        count += 1
    return count


def relative_to_known(path: Path) -> str:
    for root in (PORT_DIR, MICROPY_DIR, CANMV_DIR):
        try:
            return str(path.relative_to(root))
        except ValueError:
            pass
    return str(path)


def write_metadata(
    out_dir: Path,
    py_count: int,
    c_count: int,
    resource_lib_count: int,
    override_path: Path | None,
    overrides: OverrideMap,
    build_dir: Path | None,
    frozen_modules: list[str],
    qstr_sources: list[Path],
    analysis: CAnalysis,
) -> None:
    metadata = {
        "name": "canmv-k230-stubs",
        "description": "CanMV K230 MicroPython overlay stubs generated from source/build inventory",
        "micropython_version": micropython_version(),
        "micropython_commit": run_git(["git", "rev-parse", "--short", "HEAD"], MICROPY_DIR),
        "canmv_commit": run_git(["git", "rev-parse", "--short", "HEAD"], CANMV_DIR),
        "override_file": str(override_path) if override_path else None,
        "override_modules": len(overrides),
        "build_dir": str(build_dir) if build_dir else None,
        "frozen_modules": frozen_modules,
        "qstr_source_count": len(qstr_sources),
        "qstr_sources": [relative_to_known(path) for path in qstr_sources],
        "c_source_count": len(analysis.sources),
        "c_module_count": len(analysis.modules),
        "c_type_count": len(analysis.types),
        "c_function_count": len(analysis.functions),
        "python_stub_files": py_count,
        "c_module_stub_files": c_count,
        "resource_lib_files": resource_lib_count,
    }
    (out_dir / "canmv_stub_metadata.json").write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (out_dir / "py.typed").write_text("partial\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        default=os.environ.get("CANMV_STUB_OUT", str(CANMV_DIR / "generated" / "ide-stubs" / "canmv-k230")),
        help="output directory for generated stubs",
    )
    parser.add_argument(
        "--overrides",
        default=str(DEFAULT_OVERRIDES),
        help="JSON file with hand-written signatures and docs",
    )
    parser.add_argument(
        "--build-dir",
        default=os.environ.get("CANMV_BUILD_DIR"),
        help="optional built CanMV directory containing frozen_mpy/ and genhdr/qstr/",
    )
    parser.add_argument(
        "--manifest",
        default=os.environ.get("CANMV_MANIFEST"),
        help="board manifest.py to resolve frozen Python sources",
    )
    parser.add_argument(
        "--no-auto-build-dir",
        action="store_true",
        help="do not auto-detect output/*/canmv when --build-dir is omitted",
    )
    args = parser.parse_args(argv)

    out_dir = Path(args.out).resolve()
    override_path = Path(args.overrides).resolve() if args.overrides else None
    file_overrides = load_overrides(override_path)
    build_dir = Path(args.build_dir).resolve() if args.build_dir else None
    if build_dir is None and not args.no_auto_build_dir:
        build_dir = default_build_dir()

    manifest_path = Path(args.manifest).resolve() if args.manifest else manifest_path_from_build(build_dir)
    frozen_modules = discover_frozen_modules(build_dir)
    manifest_sources = discover_manifest_python_sources(manifest_path)
    qstr_sources = discover_qstr_sources(build_dir)
    if qstr_sources:
        qstr_sources = sorted(set(qstr_sources + discover_sibling_sources(qstr_sources)))
    analysis = analyze_c_sources(qstr_sources or fallback_sources())
    source_overrides = collect_port_doc_overrides(analysis, manifest_sources)
    overrides = merge_overrides(source_overrides, file_overrides)

    clean_output(out_dir)
    py_count = generate_python_package_stubs(out_dir, overrides, set(frozen_modules) if frozen_modules else None, manifest_sources)
    c_count = generate_c_module_stubs(out_dir, overrides, analysis)
    resource_lib_count = copy_resource_libs(out_dir)
    write_metadata(out_dir, py_count, c_count, resource_lib_count, override_path, overrides, build_dir, frozen_modules, qstr_sources, analysis)

    print(f"Generated CanMV stubs: {out_dir}")
    print(f"  Python package stubs: {py_count}")
    print(f"  C module stubs: {c_count}")
    print(f"  Resource lib files: {resource_lib_count}")
    print(f"  C modules discovered: {len(analysis.modules)}")
    print(f"  C types discovered: {len(analysis.types)}")
    print(f"  C functions discovered: {len(analysis.functions)}")
    print(f"  Override modules: {len(overrides)}")
    print(f"  Port doc override modules: {len(source_overrides)}")
    if build_dir:
        print(f"  Build inventory: {build_dir}")
        print(f"  Frozen modules: {len(frozen_modules)}")
        print(f"  QSTR sources: {len(qstr_sources)}")
    print(f"  Manifest: {manifest_path}")
    print(f"  Manifest Python sources: {len(manifest_sources)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
